#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_CameraLens_Victory_Ally

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_CameraLens_Victory_Ally.B_CameraLens_Victory_Ally_C
// 0x0000 (0x0300 - 0x0300)
class AB_CameraLens_Victory_Ally_C final : public AEmitterCameraLensEffectBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_CameraLens_Victory_Ally_C">();
	}
	static class AB_CameraLens_Victory_Ally_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_CameraLens_Victory_Ally_C>();
	}
};
static_assert(alignof(AB_CameraLens_Victory_Ally_C) == 0x000010, "Wrong alignment on AB_CameraLens_Victory_Ally_C");
static_assert(sizeof(AB_CameraLens_Victory_Ally_C) == 0x000300, "Wrong size on AB_CameraLens_Victory_Ally_C");

}

