#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleMapTimeIndicator

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleMapTimeIndicator.BP_BattleMapTimeIndicator_C
// 0x0010 (0x02B0 - 0x02A0)
class ABP_BattleMapTimeIndicator_C final : public ABattleMapTimeIndicator
{
public:
	class UStaticMeshComponent*                   Arrow;                                             // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattleMapTimeIndicator_C">();
	}
	static class ABP_BattleMapTimeIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattleMapTimeIndicator_C>();
	}
};
static_assert(alignof(ABP_BattleMapTimeIndicator_C) == 0x000008, "Wrong alignment on ABP_BattleMapTimeIndicator_C");
static_assert(sizeof(ABP_BattleMapTimeIndicator_C) == 0x0002B0, "Wrong size on ABP_BattleMapTimeIndicator_C");
static_assert(offsetof(ABP_BattleMapTimeIndicator_C, Arrow) == 0x0002A0, "Member 'ABP_BattleMapTimeIndicator_C::Arrow' has a wrong offset!");
static_assert(offsetof(ABP_BattleMapTimeIndicator_C, DefaultSceneRoot) == 0x0002A8, "Member 'ABP_BattleMapTimeIndicator_C::DefaultSceneRoot' has a wrong offset!");

}

