#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleMapZoneNode

#include "Basic.hpp"

#include "BP_BattleMapBaseNode_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleMapZoneNode.BP_BattleMapZoneNode_C
// 0x0008 (0x0378 - 0x0370)
class ABP_BattleMapZoneNode_C final : public ABP_BattleMapBaseNode_C
{
public:
	class UStaticMeshComponent*                   StaticMesh_Inverted;                               // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattleMapZoneNode_C">();
	}
	static class ABP_BattleMapZoneNode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattleMapZoneNode_C>();
	}
};
static_assert(alignof(ABP_BattleMapZoneNode_C) == 0x000008, "Wrong alignment on ABP_BattleMapZoneNode_C");
static_assert(sizeof(ABP_BattleMapZoneNode_C) == 0x000378, "Wrong size on ABP_BattleMapZoneNode_C");
static_assert(offsetof(ABP_BattleMapZoneNode_C, StaticMesh_Inverted) == 0x000370, "Member 'ABP_BattleMapZoneNode_C::StaticMesh_Inverted' has a wrong offset!");

}

