#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAT_ActiveAbility_Hero

#include "Basic.hpp"

#include "GAT_ActiveAbility_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAT_ActiveAbility_Hero.GAT_ActiveAbility_Hero_C
// 0x0010 (0x0980 - 0x0970)
class UGAT_ActiveAbility_Hero_C : public UGAT_ActiveAbility_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GAT_ActiveAbility_Hero_C;           // 0x0970(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          UseHeroLoadoutSystem;                              // 0x0978(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_GAT_ActiveAbility_Hero(int32 EntryPoint);
	void CommitAbilityWithEvent(bool* Passed);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAT_ActiveAbility_Hero_C">();
	}
	static class UGAT_ActiveAbility_Hero_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAT_ActiveAbility_Hero_C>();
	}
};
static_assert(alignof(UGAT_ActiveAbility_Hero_C) == 0x000008, "Wrong alignment on UGAT_ActiveAbility_Hero_C");
static_assert(sizeof(UGAT_ActiveAbility_Hero_C) == 0x000980, "Wrong size on UGAT_ActiveAbility_Hero_C");
static_assert(offsetof(UGAT_ActiveAbility_Hero_C, UberGraphFrame_GAT_ActiveAbility_Hero_C) == 0x000970, "Member 'UGAT_ActiveAbility_Hero_C::UberGraphFrame_GAT_ActiveAbility_Hero_C' has a wrong offset!");
static_assert(offsetof(UGAT_ActiveAbility_Hero_C, UseHeroLoadoutSystem) == 0x000978, "Member 'UGAT_ActiveAbility_Hero_C::UseHeroLoadoutSystem' has a wrong offset!");

}

