#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SiphonEffect_Heal

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SiphonEffect_Heal.GE_SiphonEffect_Heal_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_SiphonEffect_Heal_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SiphonEffect_Heal_C">();
	}
	static class UGE_SiphonEffect_Heal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SiphonEffect_Heal_C>();
	}
};
static_assert(alignof(UGE_SiphonEffect_Heal_C) == 0x000008, "Wrong alignment on UGE_SiphonEffect_Heal_C");
static_assert(sizeof(UGE_SiphonEffect_Heal_C) == 0x0005F0, "Wrong size on UGE_SiphonEffect_Heal_C");

}

