#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Niagara

#include "Basic.hpp"

#include "Niagara_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Niagara.NiagaraComponent.AdvanceSimulation
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_AdvanceSimulation final
{
public:
	int32                                         TickCount;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TickDeltaSeconds;                                  // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_AdvanceSimulation) == 0x000004, "Wrong alignment on NiagaraComponent_AdvanceSimulation");
static_assert(sizeof(NiagaraComponent_AdvanceSimulation) == 0x000008, "Wrong size on NiagaraComponent_AdvanceSimulation");
static_assert(offsetof(NiagaraComponent_AdvanceSimulation, TickCount) == 0x000000, "Member 'NiagaraComponent_AdvanceSimulation::TickCount' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_AdvanceSimulation, TickDeltaSeconds) == 0x000004, "Member 'NiagaraComponent_AdvanceSimulation::TickDeltaSeconds' has a wrong offset!");

// Function Niagara.NiagaraComponent.AdvanceSimulationByTime
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_AdvanceSimulationByTime final
{
public:
	float                                         SimulateTime;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TickDeltaSeconds;                                  // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_AdvanceSimulationByTime) == 0x000004, "Wrong alignment on NiagaraComponent_AdvanceSimulationByTime");
static_assert(sizeof(NiagaraComponent_AdvanceSimulationByTime) == 0x000008, "Wrong size on NiagaraComponent_AdvanceSimulationByTime");
static_assert(offsetof(NiagaraComponent_AdvanceSimulationByTime, SimulateTime) == 0x000000, "Member 'NiagaraComponent_AdvanceSimulationByTime::SimulateTime' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_AdvanceSimulationByTime, TickDeltaSeconds) == 0x000004, "Member 'NiagaraComponent_AdvanceSimulationByTime::TickDeltaSeconds' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetNiagaraParticlePositions_DebugOnly
// 0x0020 (0x0020 - 0x0000)
struct NiagaraComponent_GetNiagaraParticlePositions_DebugOnly final
{
public:
	class FString                                 InEmitterName;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetNiagaraParticlePositions_DebugOnly) == 0x000008, "Wrong alignment on NiagaraComponent_GetNiagaraParticlePositions_DebugOnly");
static_assert(sizeof(NiagaraComponent_GetNiagaraParticlePositions_DebugOnly) == 0x000020, "Wrong size on NiagaraComponent_GetNiagaraParticlePositions_DebugOnly");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticlePositions_DebugOnly, InEmitterName) == 0x000000, "Member 'NiagaraComponent_GetNiagaraParticlePositions_DebugOnly::InEmitterName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticlePositions_DebugOnly, ReturnValue) == 0x000010, "Member 'NiagaraComponent_GetNiagaraParticlePositions_DebugOnly::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetNiagaraParticleValues_DebugOnly
// 0x0030 (0x0030 - 0x0000)
struct NiagaraComponent_GetNiagaraParticleValues_DebugOnly final
{
public:
	class FString                                 InEmitterName;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InValueName;                                       // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetNiagaraParticleValues_DebugOnly) == 0x000008, "Wrong alignment on NiagaraComponent_GetNiagaraParticleValues_DebugOnly");
static_assert(sizeof(NiagaraComponent_GetNiagaraParticleValues_DebugOnly) == 0x000030, "Wrong size on NiagaraComponent_GetNiagaraParticleValues_DebugOnly");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValues_DebugOnly, InEmitterName) == 0x000000, "Member 'NiagaraComponent_GetNiagaraParticleValues_DebugOnly::InEmitterName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValues_DebugOnly, InValueName) == 0x000010, "Member 'NiagaraComponent_GetNiagaraParticleValues_DebugOnly::InValueName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValues_DebugOnly, ReturnValue) == 0x000020, "Member 'NiagaraComponent_GetNiagaraParticleValues_DebugOnly::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetNiagaraParticleValueVec3_DebugOnly
// 0x0030 (0x0030 - 0x0000)
struct NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly final
{
public:
	class FString                                 InEmitterName;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InValueName;                                       // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly) == 0x000008, "Wrong alignment on NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly");
static_assert(sizeof(NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly) == 0x000030, "Wrong size on NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly, InEmitterName) == 0x000000, "Member 'NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly::InEmitterName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly, InValueName) == 0x000010, "Member 'NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly::InValueName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly, ReturnValue) == 0x000020, "Member 'NiagaraComponent_GetNiagaraParticleValueVec3_DebugOnly::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SeekToDesiredAge
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_SeekToDesiredAge final
{
public:
	float                                         InDesiredAge;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SeekToDesiredAge) == 0x000004, "Wrong alignment on NiagaraComponent_SeekToDesiredAge");
static_assert(sizeof(NiagaraComponent_SeekToDesiredAge) == 0x000004, "Wrong size on NiagaraComponent_SeekToDesiredAge");
static_assert(offsetof(NiagaraComponent_SeekToDesiredAge, InDesiredAge) == 0x000000, "Member 'NiagaraComponent_SeekToDesiredAge::InDesiredAge' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetAgeUpdateMode
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetAgeUpdateMode final
{
public:
	ENiagaraAgeUpdateMode                         InAgeUpdateMode;                                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetAgeUpdateMode) == 0x000001, "Wrong alignment on NiagaraComponent_SetAgeUpdateMode");
static_assert(sizeof(NiagaraComponent_SetAgeUpdateMode) == 0x000001, "Wrong size on NiagaraComponent_SetAgeUpdateMode");
static_assert(offsetof(NiagaraComponent_SetAgeUpdateMode, InAgeUpdateMode) == 0x000000, "Member 'NiagaraComponent_SetAgeUpdateMode::InAgeUpdateMode' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetAsset
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_SetAsset final
{
public:
	class UNiagaraSystem*                         InAsset;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetAsset) == 0x000008, "Wrong alignment on NiagaraComponent_SetAsset");
static_assert(sizeof(NiagaraComponent_SetAsset) == 0x000008, "Wrong size on NiagaraComponent_SetAsset");
static_assert(offsetof(NiagaraComponent_SetAsset, InAsset) == 0x000000, "Member 'NiagaraComponent_SetAsset::InAsset' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetAutoAttachmentParameters
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetAutoAttachmentParameters final
{
public:
	class USceneComponent*                        Parent;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   SocketName;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAttachmentRule                               LocationRule;                                      // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAttachmentRule                               RotationRule;                                      // 0x0011(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAttachmentRule                               ScaleRule;                                         // 0x0012(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraComponent_SetAutoAttachmentParameters) == 0x000008, "Wrong alignment on NiagaraComponent_SetAutoAttachmentParameters");
static_assert(sizeof(NiagaraComponent_SetAutoAttachmentParameters) == 0x000018, "Wrong size on NiagaraComponent_SetAutoAttachmentParameters");
static_assert(offsetof(NiagaraComponent_SetAutoAttachmentParameters, Parent) == 0x000000, "Member 'NiagaraComponent_SetAutoAttachmentParameters::Parent' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetAutoAttachmentParameters, SocketName) == 0x000008, "Member 'NiagaraComponent_SetAutoAttachmentParameters::SocketName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetAutoAttachmentParameters, LocationRule) == 0x000010, "Member 'NiagaraComponent_SetAutoAttachmentParameters::LocationRule' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetAutoAttachmentParameters, RotationRule) == 0x000011, "Member 'NiagaraComponent_SetAutoAttachmentParameters::RotationRule' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetAutoAttachmentParameters, ScaleRule) == 0x000012, "Member 'NiagaraComponent_SetAutoAttachmentParameters::ScaleRule' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetAutoDestroy
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetAutoDestroy final
{
public:
	bool                                          bInAutoDestroy;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetAutoDestroy) == 0x000001, "Wrong alignment on NiagaraComponent_SetAutoDestroy");
static_assert(sizeof(NiagaraComponent_SetAutoDestroy) == 0x000001, "Wrong size on NiagaraComponent_SetAutoDestroy");
static_assert(offsetof(NiagaraComponent_SetAutoDestroy, bInAutoDestroy) == 0x000000, "Member 'NiagaraComponent_SetAutoDestroy::bInAutoDestroy' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetCanRenderWhileSeeking
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetCanRenderWhileSeeking final
{
public:
	bool                                          bInCanRenderWhileSeeking;                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetCanRenderWhileSeeking) == 0x000001, "Wrong alignment on NiagaraComponent_SetCanRenderWhileSeeking");
static_assert(sizeof(NiagaraComponent_SetCanRenderWhileSeeking) == 0x000001, "Wrong size on NiagaraComponent_SetCanRenderWhileSeeking");
static_assert(offsetof(NiagaraComponent_SetCanRenderWhileSeeking, bInCanRenderWhileSeeking) == 0x000000, "Member 'NiagaraComponent_SetCanRenderWhileSeeking::bInCanRenderWhileSeeking' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetDesiredAge
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_SetDesiredAge final
{
public:
	float                                         InDesiredAge;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetDesiredAge) == 0x000004, "Wrong alignment on NiagaraComponent_SetDesiredAge");
static_assert(sizeof(NiagaraComponent_SetDesiredAge) == 0x000004, "Wrong size on NiagaraComponent_SetDesiredAge");
static_assert(offsetof(NiagaraComponent_SetDesiredAge, InDesiredAge) == 0x000000, "Member 'NiagaraComponent_SetDesiredAge::InDesiredAge' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetForceSolo
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetForceSolo final
{
public:
	bool                                          bInForceSolo;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetForceSolo) == 0x000001, "Wrong alignment on NiagaraComponent_SetForceSolo");
static_assert(sizeof(NiagaraComponent_SetForceSolo) == 0x000001, "Wrong size on NiagaraComponent_SetForceSolo");
static_assert(offsetof(NiagaraComponent_SetForceSolo, bInForceSolo) == 0x000000, "Member 'NiagaraComponent_SetForceSolo::bInForceSolo' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetMaxSimTime
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_SetMaxSimTime final
{
public:
	float                                         InMaxTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetMaxSimTime) == 0x000004, "Wrong alignment on NiagaraComponent_SetMaxSimTime");
static_assert(sizeof(NiagaraComponent_SetMaxSimTime) == 0x000004, "Wrong size on NiagaraComponent_SetMaxSimTime");
static_assert(offsetof(NiagaraComponent_SetMaxSimTime, InMaxTime) == 0x000000, "Member 'NiagaraComponent_SetMaxSimTime::InMaxTime' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableActor
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableActor final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Actor;                                             // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableActor) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableActor");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableActor) == 0x000018, "Wrong size on NiagaraComponent_SetNiagaraVariableActor");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableActor, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableActor::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableActor, Actor) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableActor::Actor' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableBool
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableBool final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InValue;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableBool) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableBool");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableBool) == 0x000018, "Wrong size on NiagaraComponent_SetNiagaraVariableBool");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableBool, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableBool::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableBool, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableBool::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableFloat
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableFloat final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InValue;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableFloat) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableFloat");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableFloat) == 0x000018, "Wrong size on NiagaraComponent_SetNiagaraVariableFloat");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableFloat, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableFloat::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableFloat, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableFloat::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableInt
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableInt final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InValue;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableInt) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableInt");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableInt) == 0x000018, "Wrong size on NiagaraComponent_SetNiagaraVariableInt");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableInt, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableInt::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableInt, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableInt::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableLinearColor
// 0x0020 (0x0020 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableLinearColor final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           InValue;                                           // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableLinearColor) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableLinearColor");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableLinearColor) == 0x000020, "Wrong size on NiagaraComponent_SetNiagaraVariableLinearColor");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableLinearColor, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableLinearColor::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableLinearColor, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableLinearColor::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableQuat
// 0x0020 (0x0020 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableQuat final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FQuat                                  InValue;                                           // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableQuat) == 0x000010, "Wrong alignment on NiagaraComponent_SetNiagaraVariableQuat");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableQuat) == 0x000020, "Wrong size on NiagaraComponent_SetNiagaraVariableQuat");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableQuat, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableQuat::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableQuat, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableQuat::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableVec2
// 0x0018 (0x0018 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableVec2 final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              InValue;                                           // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableVec2) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableVec2");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableVec2) == 0x000018, "Wrong size on NiagaraComponent_SetNiagaraVariableVec2");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec2, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableVec2::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec2, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableVec2::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableVec3
// 0x0020 (0x0020 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableVec3 final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                InValue;                                           // 0x0010(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableVec3) == 0x000008, "Wrong alignment on NiagaraComponent_SetNiagaraVariableVec3");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableVec3) == 0x000020, "Wrong size on NiagaraComponent_SetNiagaraVariableVec3");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec3, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableVec3::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec3, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableVec3::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetNiagaraVariableVec4
// 0x0020 (0x0020 - 0x0000)
struct NiagaraComponent_SetNiagaraVariableVec4 final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector4                               InValue;                                           // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetNiagaraVariableVec4) == 0x000010, "Wrong alignment on NiagaraComponent_SetNiagaraVariableVec4");
static_assert(sizeof(NiagaraComponent_SetNiagaraVariableVec4) == 0x000020, "Wrong size on NiagaraComponent_SetNiagaraVariableVec4");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec4, InVariableName) == 0x000000, "Member 'NiagaraComponent_SetNiagaraVariableVec4::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetNiagaraVariableVec4, InValue) == 0x000010, "Member 'NiagaraComponent_SetNiagaraVariableVec4::InValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetPaused
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetPaused final
{
public:
	bool                                          bInPaused;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetPaused) == 0x000001, "Wrong alignment on NiagaraComponent_SetPaused");
static_assert(sizeof(NiagaraComponent_SetPaused) == 0x000001, "Wrong size on NiagaraComponent_SetPaused");
static_assert(offsetof(NiagaraComponent_SetPaused, bInPaused) == 0x000000, "Member 'NiagaraComponent_SetPaused::bInPaused' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetPreviewDetailLevel
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_SetPreviewDetailLevel final
{
public:
	bool                                          Param_bEnablePreviewDetailLevel;                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Param_PreviewDetailLevel;                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetPreviewDetailLevel) == 0x000004, "Wrong alignment on NiagaraComponent_SetPreviewDetailLevel");
static_assert(sizeof(NiagaraComponent_SetPreviewDetailLevel) == 0x000008, "Wrong size on NiagaraComponent_SetPreviewDetailLevel");
static_assert(offsetof(NiagaraComponent_SetPreviewDetailLevel, Param_bEnablePreviewDetailLevel) == 0x000000, "Member 'NiagaraComponent_SetPreviewDetailLevel::Param_bEnablePreviewDetailLevel' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetPreviewDetailLevel, Param_PreviewDetailLevel) == 0x000004, "Member 'NiagaraComponent_SetPreviewDetailLevel::Param_PreviewDetailLevel' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetPreviewLODDistance
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_SetPreviewLODDistance final
{
public:
	bool                                          Param_bEnablePreviewLODDistance;                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Param_PreviewLODDistance;                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetPreviewLODDistance) == 0x000004, "Wrong alignment on NiagaraComponent_SetPreviewLODDistance");
static_assert(sizeof(NiagaraComponent_SetPreviewLODDistance) == 0x000008, "Wrong size on NiagaraComponent_SetPreviewLODDistance");
static_assert(offsetof(NiagaraComponent_SetPreviewLODDistance, Param_bEnablePreviewLODDistance) == 0x000000, "Member 'NiagaraComponent_SetPreviewLODDistance::Param_bEnablePreviewLODDistance' has a wrong offset!");
static_assert(offsetof(NiagaraComponent_SetPreviewLODDistance, Param_PreviewLODDistance) == 0x000004, "Member 'NiagaraComponent_SetPreviewLODDistance::Param_PreviewLODDistance' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetRenderingEnabled
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_SetRenderingEnabled final
{
public:
	bool                                          bInRenderingEnabled;                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetRenderingEnabled) == 0x000001, "Wrong alignment on NiagaraComponent_SetRenderingEnabled");
static_assert(sizeof(NiagaraComponent_SetRenderingEnabled) == 0x000001, "Wrong size on NiagaraComponent_SetRenderingEnabled");
static_assert(offsetof(NiagaraComponent_SetRenderingEnabled, bInRenderingEnabled) == 0x000000, "Member 'NiagaraComponent_SetRenderingEnabled::bInRenderingEnabled' has a wrong offset!");

// Function Niagara.NiagaraComponent.SetSeekDelta
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_SetSeekDelta final
{
public:
	float                                         InSeekDelta;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_SetSeekDelta) == 0x000004, "Wrong alignment on NiagaraComponent_SetSeekDelta");
static_assert(sizeof(NiagaraComponent_SetSeekDelta) == 0x000004, "Wrong size on NiagaraComponent_SetSeekDelta");
static_assert(offsetof(NiagaraComponent_SetSeekDelta, InSeekDelta) == 0x000000, "Member 'NiagaraComponent_SetSeekDelta::InSeekDelta' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetAgeUpdateMode
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_GetAgeUpdateMode final
{
public:
	ENiagaraAgeUpdateMode                         ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetAgeUpdateMode) == 0x000001, "Wrong alignment on NiagaraComponent_GetAgeUpdateMode");
static_assert(sizeof(NiagaraComponent_GetAgeUpdateMode) == 0x000001, "Wrong size on NiagaraComponent_GetAgeUpdateMode");
static_assert(offsetof(NiagaraComponent_GetAgeUpdateMode, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetAgeUpdateMode::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetAsset
// 0x0008 (0x0008 - 0x0000)
struct NiagaraComponent_GetAsset final
{
public:
	class UNiagaraSystem*                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetAsset) == 0x000008, "Wrong alignment on NiagaraComponent_GetAsset");
static_assert(sizeof(NiagaraComponent_GetAsset) == 0x000008, "Wrong size on NiagaraComponent_GetAsset");
static_assert(offsetof(NiagaraComponent_GetAsset, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetAsset::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetDesiredAge
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_GetDesiredAge final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetDesiredAge) == 0x000004, "Wrong alignment on NiagaraComponent_GetDesiredAge");
static_assert(sizeof(NiagaraComponent_GetDesiredAge) == 0x000004, "Wrong size on NiagaraComponent_GetDesiredAge");
static_assert(offsetof(NiagaraComponent_GetDesiredAge, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetDesiredAge::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetForceSolo
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_GetForceSolo final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetForceSolo) == 0x000001, "Wrong alignment on NiagaraComponent_GetForceSolo");
static_assert(sizeof(NiagaraComponent_GetForceSolo) == 0x000001, "Wrong size on NiagaraComponent_GetForceSolo");
static_assert(offsetof(NiagaraComponent_GetForceSolo, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetForceSolo::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetMaxSimTime
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_GetMaxSimTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetMaxSimTime) == 0x000004, "Wrong alignment on NiagaraComponent_GetMaxSimTime");
static_assert(sizeof(NiagaraComponent_GetMaxSimTime) == 0x000004, "Wrong size on NiagaraComponent_GetMaxSimTime");
static_assert(offsetof(NiagaraComponent_GetMaxSimTime, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetMaxSimTime::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.GetSeekDelta
// 0x0004 (0x0004 - 0x0000)
struct NiagaraComponent_GetSeekDelta final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_GetSeekDelta) == 0x000004, "Wrong alignment on NiagaraComponent_GetSeekDelta");
static_assert(sizeof(NiagaraComponent_GetSeekDelta) == 0x000004, "Wrong size on NiagaraComponent_GetSeekDelta");
static_assert(offsetof(NiagaraComponent_GetSeekDelta, ReturnValue) == 0x000000, "Member 'NiagaraComponent_GetSeekDelta::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraComponent.IsPaused
// 0x0001 (0x0001 - 0x0000)
struct NiagaraComponent_IsPaused final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraComponent_IsPaused) == 0x000001, "Wrong alignment on NiagaraComponent_IsPaused");
static_assert(sizeof(NiagaraComponent_IsPaused) == 0x000001, "Wrong size on NiagaraComponent_IsPaused");
static_assert(offsetof(NiagaraComponent_IsPaused, ReturnValue) == 0x000000, "Member 'NiagaraComponent_IsPaused::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.GetNiagaraParameterCollection
// 0x0018 (0x0018 - 0x0000)
struct NiagaraFunctionLibrary_GetNiagaraParameterCollection final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraParameterCollection*            Collection;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraParameterCollectionInstance*    ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_GetNiagaraParameterCollection) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_GetNiagaraParameterCollection");
static_assert(sizeof(NiagaraFunctionLibrary_GetNiagaraParameterCollection) == 0x000018, "Wrong size on NiagaraFunctionLibrary_GetNiagaraParameterCollection");
static_assert(offsetof(NiagaraFunctionLibrary_GetNiagaraParameterCollection, WorldContextObject) == 0x000000, "Member 'NiagaraFunctionLibrary_GetNiagaraParameterCollection::WorldContextObject' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_GetNiagaraParameterCollection, Collection) == 0x000008, "Member 'NiagaraFunctionLibrary_GetNiagaraParameterCollection::Collection' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_GetNiagaraParameterCollection, ReturnValue) == 0x000010, "Member 'NiagaraFunctionLibrary_GetNiagaraParameterCollection::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.OverrideSystemUserVariableSkeletalMeshComponent
// 0x0020 (0x0020 - 0x0000)
struct NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent final
{
public:
	class UNiagaraComponent*                      NiagaraSystem;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OverrideName;                                      // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 SkeletalMeshComponent;                             // 0x0018(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent");
static_assert(sizeof(NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent) == 0x000020, "Wrong size on NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent, NiagaraSystem) == 0x000000, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent::NiagaraSystem' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent, OverrideName) == 0x000008, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent::OverrideName' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent, SkeletalMeshComponent) == 0x000018, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableSkeletalMeshComponent::SkeletalMeshComponent' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.OverrideSystemUserVariableStaticMesh
// 0x0020 (0x0020 - 0x0000)
struct NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh final
{
public:
	class UNiagaraComponent*                      NiagaraSystem;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OverrideName;                                      // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMesh*                            StaticMesh;                                        // 0x0018(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh");
static_assert(sizeof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh) == 0x000020, "Wrong size on NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh, NiagaraSystem) == 0x000000, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh::NiagaraSystem' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh, OverrideName) == 0x000008, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh::OverrideName' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh, StaticMesh) == 0x000018, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMesh::StaticMesh' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.OverrideSystemUserVariableStaticMeshComponent
// 0x0020 (0x0020 - 0x0000)
struct NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent final
{
public:
	class UNiagaraComponent*                      NiagaraSystem;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OverrideName;                                      // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMeshComponent*                   StaticMeshComponent;                               // 0x0018(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent");
static_assert(sizeof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent) == 0x000020, "Wrong size on NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent, NiagaraSystem) == 0x000000, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent::NiagaraSystem' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent, OverrideName) == 0x000008, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent::OverrideName' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent, StaticMeshComponent) == 0x000018, "Member 'NiagaraFunctionLibrary_OverrideSystemUserVariableStaticMeshComponent::StaticMeshComponent' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.SpawnSystemAtLocation
// 0x0038 (0x0038 - 0x0000)
struct NiagaraFunctionLibrary_SpawnSystemAtLocation final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         SystemTemplate;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Location;                                          // 0x0010(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Rotation;                                          // 0x001C(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bAutoDestroy;                                      // 0x0028(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      ReturnValue;                                       // 0x0030(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_SpawnSystemAtLocation) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_SpawnSystemAtLocation");
static_assert(sizeof(NiagaraFunctionLibrary_SpawnSystemAtLocation) == 0x000038, "Wrong size on NiagaraFunctionLibrary_SpawnSystemAtLocation");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, WorldContextObject) == 0x000000, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::WorldContextObject' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, SystemTemplate) == 0x000008, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::SystemTemplate' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, Location) == 0x000010, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::Location' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, Rotation) == 0x00001C, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::Rotation' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, bAutoDestroy) == 0x000028, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::bAutoDestroy' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAtLocation, ReturnValue) == 0x000030, "Member 'NiagaraFunctionLibrary_SpawnSystemAtLocation::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraFunctionLibrary.SpawnSystemAttached
// 0x0040 (0x0040 - 0x0000)
struct NiagaraFunctionLibrary_SpawnSystemAttached final
{
public:
	class UNiagaraSystem*                         SystemTemplate;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USceneComponent*                        AttachToComponent;                                 // 0x0008(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AttachPointName;                                   // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Location;                                          // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Rotation;                                          // 0x0024(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	EAttachLocation                               LocationType;                                      // 0x0030(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoDestroy;                                      // 0x0031(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      ReturnValue;                                       // 0x0038(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraFunctionLibrary_SpawnSystemAttached) == 0x000008, "Wrong alignment on NiagaraFunctionLibrary_SpawnSystemAttached");
static_assert(sizeof(NiagaraFunctionLibrary_SpawnSystemAttached) == 0x000040, "Wrong size on NiagaraFunctionLibrary_SpawnSystemAttached");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, SystemTemplate) == 0x000000, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::SystemTemplate' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, AttachToComponent) == 0x000008, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::AttachToComponent' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, AttachPointName) == 0x000010, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::AttachPointName' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, Location) == 0x000018, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::Location' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, Rotation) == 0x000024, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::Rotation' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, LocationType) == 0x000030, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::LocationType' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, bAutoDestroy) == 0x000031, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::bAutoDestroy' has a wrong offset!");
static_assert(offsetof(NiagaraFunctionLibrary_SpawnSystemAttached, ReturnValue) == 0x000038, "Member 'NiagaraFunctionLibrary_SpawnSystemAttached::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetBoolParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_GetBoolParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetBoolParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetBoolParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetBoolParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_GetBoolParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetBoolParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetBoolParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetBoolParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetBoolParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetColorParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_GetColorParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetColorParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetColorParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetColorParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_GetColorParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetColorParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetColorParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetColorParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetColorParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetFloatParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_GetFloatParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetFloatParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetFloatParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetFloatParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_GetFloatParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetFloatParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetFloatParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetFloatParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetFloatParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetIntParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_GetIntParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetIntParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetIntParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetIntParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_GetIntParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetIntParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetIntParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetIntParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetIntParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetQuatParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_GetQuatParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FQuat                                  ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetQuatParameter) == 0x000010, "Wrong alignment on NiagaraParameterCollectionInstance_GetQuatParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetQuatParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_GetQuatParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetQuatParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetQuatParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetQuatParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetQuatParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetVector2DParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_GetVector2DParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetVector2DParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetVector2DParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetVector2DParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_GetVector2DParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVector2DParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetVector2DParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVector2DParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetVector2DParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetVector4Parameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_GetVector4Parameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector4                               ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetVector4Parameter) == 0x000010, "Wrong alignment on NiagaraParameterCollectionInstance_GetVector4Parameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetVector4Parameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_GetVector4Parameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVector4Parameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetVector4Parameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVector4Parameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetVector4Parameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.GetVectorParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_GetVectorParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0010(0x000C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_GetVectorParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_GetVectorParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_GetVectorParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_GetVectorParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVectorParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_GetVectorParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_GetVectorParameter, ReturnValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_GetVectorParameter::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetBoolParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_SetBoolParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InValue;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetBoolParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetBoolParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetBoolParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_SetBoolParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetBoolParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetBoolParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetBoolParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetBoolParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetColorParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_SetColorParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           InValue;                                           // 0x0010(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetColorParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetColorParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetColorParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_SetColorParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetColorParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetColorParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetColorParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetColorParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetFloatParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_SetFloatParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InValue;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetFloatParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetFloatParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetFloatParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_SetFloatParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetFloatParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetFloatParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetFloatParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetFloatParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetIntParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_SetIntParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InValue;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetIntParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetIntParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetIntParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_SetIntParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetIntParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetIntParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetIntParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetIntParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetQuatParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_SetQuatParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FQuat                                  InValue;                                           // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetQuatParameter) == 0x000010, "Wrong alignment on NiagaraParameterCollectionInstance_SetQuatParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetQuatParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_SetQuatParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetQuatParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetQuatParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetQuatParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetQuatParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetVector2DParameter
// 0x0018 (0x0018 - 0x0000)
struct NiagaraParameterCollectionInstance_SetVector2DParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              InValue;                                           // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetVector2DParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetVector2DParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetVector2DParameter) == 0x000018, "Wrong size on NiagaraParameterCollectionInstance_SetVector2DParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVector2DParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetVector2DParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVector2DParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetVector2DParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetVector4Parameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_SetVector4Parameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector4                               InValue;                                           // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetVector4Parameter) == 0x000010, "Wrong alignment on NiagaraParameterCollectionInstance_SetVector4Parameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetVector4Parameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_SetVector4Parameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVector4Parameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetVector4Parameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVector4Parameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetVector4Parameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraParameterCollectionInstance.SetVectorParameter
// 0x0020 (0x0020 - 0x0000)
struct NiagaraParameterCollectionInstance_SetVectorParameter final
{
public:
	class FString                                 InVariableName;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                InValue;                                           // 0x0010(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(NiagaraParameterCollectionInstance_SetVectorParameter) == 0x000008, "Wrong alignment on NiagaraParameterCollectionInstance_SetVectorParameter");
static_assert(sizeof(NiagaraParameterCollectionInstance_SetVectorParameter) == 0x000020, "Wrong size on NiagaraParameterCollectionInstance_SetVectorParameter");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVectorParameter, InVariableName) == 0x000000, "Member 'NiagaraParameterCollectionInstance_SetVectorParameter::InVariableName' has a wrong offset!");
static_assert(offsetof(NiagaraParameterCollectionInstance_SetVectorParameter, InValue) == 0x000010, "Member 'NiagaraParameterCollectionInstance_SetVectorParameter::InValue' has a wrong offset!");

// Function Niagara.NiagaraPreviewBase.SetLabelText
// 0x0030 (0x0030 - 0x0000)
struct NiagaraPreviewBase_SetLabelText final
{
public:
	class FText                                   InXAxisText;                                       // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FText                                   InYAxisText;                                       // 0x0018(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraPreviewBase_SetLabelText) == 0x000008, "Wrong alignment on NiagaraPreviewBase_SetLabelText");
static_assert(sizeof(NiagaraPreviewBase_SetLabelText) == 0x000030, "Wrong size on NiagaraPreviewBase_SetLabelText");
static_assert(offsetof(NiagaraPreviewBase_SetLabelText, InXAxisText) == 0x000000, "Member 'NiagaraPreviewBase_SetLabelText::InXAxisText' has a wrong offset!");
static_assert(offsetof(NiagaraPreviewBase_SetLabelText, InYAxisText) == 0x000018, "Member 'NiagaraPreviewBase_SetLabelText::InYAxisText' has a wrong offset!");

// Function Niagara.NiagaraPreviewBase.SetSystem
// 0x0008 (0x0008 - 0x0000)
struct NiagaraPreviewBase_SetSystem final
{
public:
	class UNiagaraSystem*                         InSystem;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraPreviewBase_SetSystem) == 0x000008, "Wrong alignment on NiagaraPreviewBase_SetSystem");
static_assert(sizeof(NiagaraPreviewBase_SetSystem) == 0x000008, "Wrong size on NiagaraPreviewBase_SetSystem");
static_assert(offsetof(NiagaraPreviewBase_SetSystem, InSystem) == 0x000000, "Member 'NiagaraPreviewBase_SetSystem::InSystem' has a wrong offset!");

// Function Niagara.NiagaraPreviewAxis.ApplyToPreview
// 0x0020 (0x0020 - 0x0000)
struct NiagaraPreviewAxis_ApplyToPreview final
{
public:
	class UNiagaraComponent*                      PreviewComponent;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PreviewIndex;                                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsXAxis;                                          // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 OutLabelText;                                      // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraPreviewAxis_ApplyToPreview) == 0x000008, "Wrong alignment on NiagaraPreviewAxis_ApplyToPreview");
static_assert(sizeof(NiagaraPreviewAxis_ApplyToPreview) == 0x000020, "Wrong size on NiagaraPreviewAxis_ApplyToPreview");
static_assert(offsetof(NiagaraPreviewAxis_ApplyToPreview, PreviewComponent) == 0x000000, "Member 'NiagaraPreviewAxis_ApplyToPreview::PreviewComponent' has a wrong offset!");
static_assert(offsetof(NiagaraPreviewAxis_ApplyToPreview, PreviewIndex) == 0x000008, "Member 'NiagaraPreviewAxis_ApplyToPreview::PreviewIndex' has a wrong offset!");
static_assert(offsetof(NiagaraPreviewAxis_ApplyToPreview, bIsXAxis) == 0x00000C, "Member 'NiagaraPreviewAxis_ApplyToPreview::bIsXAxis' has a wrong offset!");
static_assert(offsetof(NiagaraPreviewAxis_ApplyToPreview, OutLabelText) == 0x000010, "Member 'NiagaraPreviewAxis_ApplyToPreview::OutLabelText' has a wrong offset!");

// Function Niagara.NiagaraPreviewAxis.Num
// 0x0004 (0x0004 - 0x0000)
struct NiagaraPreviewAxis_Num final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraPreviewAxis_Num) == 0x000004, "Wrong alignment on NiagaraPreviewAxis_Num");
static_assert(sizeof(NiagaraPreviewAxis_Num) == 0x000004, "Wrong size on NiagaraPreviewAxis_Num");
static_assert(offsetof(NiagaraPreviewAxis_Num, ReturnValue) == 0x000000, "Member 'NiagaraPreviewAxis_Num::ReturnValue' has a wrong offset!");

// Function Niagara.NiagaraPreviewGrid.ActivatePreviews
// 0x0001 (0x0001 - 0x0000)
struct NiagaraPreviewGrid_ActivatePreviews final
{
public:
	bool                                          bReset;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(NiagaraPreviewGrid_ActivatePreviews) == 0x000001, "Wrong alignment on NiagaraPreviewGrid_ActivatePreviews");
static_assert(sizeof(NiagaraPreviewGrid_ActivatePreviews) == 0x000001, "Wrong size on NiagaraPreviewGrid_ActivatePreviews");
static_assert(offsetof(NiagaraPreviewGrid_ActivatePreviews, bReset) == 0x000000, "Member 'NiagaraPreviewGrid_ActivatePreviews::bReset' has a wrong offset!");

}

